name:                openedx
version:             0.1.0.0
github:              "Xiswa/openedx"
license:             BSD3
author:              "PT Xiswa Adidaya Nusantara"
maintainer:          "developer@xiswa.com"
copyright:           "2023 PT Xiswa Adidaya Nusantara"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Xiswa/openedx#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- aeson
- servant
- servant-client
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  openedx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - openedx
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - http-client
    - http-client-tls
